# Generated by Django 2.1.1 on 2018-09-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteor',
            name='velocity',
        ),
        migrations.AddField(
            model_name='meteor',
            name='velocityX',
            field=models.FloatField(blank=True, null=True, verbose_name='geocentric velocity at infinity, x'),
        ),
        migrations.AddField(
            model_name='meteor',
            name='velocityY',
            field=models.FloatField(blank=True, null=True, verbose_name='geocentric velocity at infinity, y'),
        ),
        migrations.AddField(
            model_name='meteor',
            name='velocityZ',
            field=models.FloatField(blank=True, null=True, verbose_name='geocentric velocity at infinity, z'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='celestial.Location', verbose_name='observer location'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='meteor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='meteors.Meteor'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='observer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='celestial.Observer', verbose_name='observer'),
        ),
        migrations.AlterField(
            model_name='videoframe',
            name='sighting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meteors.Sighting'),
        ),
    ]
