# Generated by Django 2.1.5 on 2019-01-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='location',
            new_name='station',
        ),
    ]
