# Generated by Django 2.2 on 2019-04-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0010_auto_20190408_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='composite',
            field=models.ImageField(blank=True, null=True, upload_to='sightings'),
        ),
    ]
