# Generated by Django 2.2 on 2019-04-16 12:30

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0012_auto_20190416_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteor',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='name'),
        ),
    ]
