# Generated by Django 2.2 on 2019-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0014_auto_20190419_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
