# Generated by Django 2.2 on 2019-04-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0015_auto_20190420_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='azimuth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='x',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='y',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='surrogate key'),
        ),
    ]
