# Generated by Django 2.2 on 2019-04-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0016_auto_20190420_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
