# Generated by Django 2.2 on 2019-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0017_frame_magnitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
