# Generated by Django 2.2 on 2019-04-25 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0018_frame_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sighting',
            options={'ordering': ['timestamp'], 'verbose_name': 'meteor sighting'},
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='beginningAltitude',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='beginningAzimuth',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='beginningTime',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='endAltitude',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='endAzimuth',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='lightmaxAltitude',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='lightmaxAzimuth',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='lightmaxTime',
        ),
        migrations.AddField(
            model_name='sighting',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='timestamp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frame',
            name='sighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='meteors.Sighting'),
        ),
    ]
