# Generated by Django 2.2 on 2019-04-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0019_auto_20190425_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='magnitude',
        ),
    ]
