# Generated by Django 2.2 on 2019-05-02 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0020_remove_sighting_magnitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteor',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 12, 35, 2, 987249), verbose_name='timestamp'),
            preserve_default=False,
        ),
    ]
