# Generated by Django 2.2.3 on 2019-07-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0027_auto_20190717_1312'),
        ('meteors', '0022_auto_20190502_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteor',
            name='subnetwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.Subnetwork', verbose_name='subnetwork'),
        ),
    ]
