# Generated by Django 2.2.3 on 2019-07-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0023_meteor_subnetwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={'get_latest_by': 'timestamp', 'ordering': ['sighting__id', 'order'], 'verbose_name': 'sighting frame'},
        ),
        migrations.AlterModelOptions(
            name='sighting',
            options={'get_latest_by': 'timestamp', 'ordering': ['timestamp'], 'verbose_name': 'meteor sighting'},
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='lunarElongation',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='solarElongation',
        ),
        migrations.AddField(
            model_name='frame',
            name='lunarElongation',
            field=models.FloatField(blank=True, null=True, verbose_name='lunar elongation'),
        ),
        migrations.AddField(
            model_name='frame',
            name='solarElongation',
            field=models.FloatField(blank=True, null=True, verbose_name='solar elongation'),
        ),
    ]
