# Generated by Django 2.2.5 on 2019-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0025_auto_20191030_1018'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='frame',
            name='frameOrdering',
        ),
        migrations.RemoveIndex(
            model_name='frame',
            name='sightingOrder',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='lunarElongation',
            new_name='lunar_elongation',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='solarElongation',
            new_name='solar_elongation',
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['sighting', 'order'], name='sighting_order'),
        ),
        migrations.AddConstraint(
            model_name='frame',
            constraint=models.UniqueConstraint(fields=('sighting', 'order'), name='frame_ordering'),
        ),
    ]
