# Generated by Django 2.2.7 on 2019-11-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0028_auto_20191030_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meteor',
            options={'ordering': ['timestamp'], 'verbose_name': 'meteor'},
        ),
    ]
