# Generated by Django 2.2.7 on 2019-11-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0030_auto_20191119_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteor',
            name='beginning_altitude',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='beginning_latitude',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='beginning_longitude',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='beginning_time',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='end_altitude',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='end_latitude',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='end_longitude',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='lightmax_altitude',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='lightmax_latitude',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='lightmax_longitude',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='lightmax_time',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='velocity_x',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='velocity_y',
        ),
        migrations.RemoveField(
            model_name='meteor',
            name='velocity_z',
        ),
    ]
