# Generated by Django 2.2.7 on 2019-11-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0031_auto_20191121_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteorSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='altitude')),
                ('velocity_x', models.FloatField(blank=True, null=True, verbose_name='velocity in the x direction')),
                ('velocity_y', models.FloatField(blank=True, null=True, verbose_name='velocity in the y direction')),
                ('velocity_z', models.FloatField(blank=True, null=True, verbose_name='velocity in the z direction')),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='absolute magnitude')),
                ('meteor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='meteors.Meteor', verbose_name='meteor')),
            ],
            options={
                'verbose_name': 'meteor snapshot',
                'ordering': ['meteor', 'timestamp'],
            },
        ),
    ]
