# Generated by Django 2.2.7 on 2019-11-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0032_meteorsnapshot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeteorSnapshot',
            new_name='Snapshot',
        ),
    ]
