# Generated by Django 2.2.7 on 2019-11-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0033_auto_20191121_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['meteor', 'order'], name='meteor_order'),
        ),
        migrations.AddConstraint(
            model_name='snapshot',
            constraint=models.UniqueConstraint(fields=('meteor', 'order'), name='snapshot_ordering'),
        ),
    ]
