# Generated by Django 3.0 on 2020-01-17 12:01

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0034_auto_20191121_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteor',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='name'),
        ),
    ]
