# Generated by Django 3.0.8 on 2020-07-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0035_auto_20200117_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteor',
            name='magnitude',
        ),
    ]
