# Generated by Django 3.1 on 2020-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0036_remove_meteor_magnitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='angular_speed',
        ),
        migrations.AddField(
            model_name='frame',
            name='angular_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='observed angular speed [°/s]'),
        ),
    ]
