# Generated by Django 3.1.1 on 2020-11-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0038_auto_20200918_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='composite',
        ),
        migrations.AddField(
            model_name='sighting',
            name='jpg',
            field=models.ImageField(blank=True, null=True, upload_to='sightings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='xml',
            field=models.FileField(blank=True, null=True, upload_to='sightings/%Y/%m/%d/'),
        ),
    ]
