# Generated by Django 3.1.3 on 2020-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0039_auto_20201130_1536'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sighting',
            index=models.Index(fields=['station', 'timestamp'], name='by_station'),
        ),
    ]
