# Generated by Django 3.1.3 on 2020-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0040_auto_20201207_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='avi_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
