# Generated by Django 2.1.5 on 2019-01-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_station_founded'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(default='', help_text='Printable full address', max_length=256),
            preserve_default=False,
        ),
    ]
