# Generated by Django 2.1.5 on 2019-01-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_auto_20190112_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['created'], 'verbose_name': 'log entry', 'verbose_name_plural': 'log entries'},
        ),
    ]
