# Generated by Django 2.1.5 on 2019-01-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'observer',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='A simple code, composed of 2-4 letters', max_length=8, unique=True)),
                ('name', models.CharField(help_text='Printable, user-friendly name of the station', max_length=64, unique=True)),
                ('latitude', models.FloatField(blank=True, help_text='[-90°, 90°], north positive', null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, help_text='[-180°, 180°], east positive', null=True, verbose_name='longitude')),
                ('altitude', models.FloatField(blank=True, help_text='metres above mean sea level', null=True, verbose_name='altitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Country')),
            ],
            options={
                'verbose_name': 'station',
            },
        ),
        migrations.CreateModel(
            name='Subnetwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'subnetwork',
            },
        ),
    ]
