# Generated by Django 2.1.5 on 2019-01-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_subnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='founded',
            field=models.DateField(blank=True, help_text='date when observatory was founded', null=True, verbose_name='founding date'),
        ),
    ]
