# Generated by Django 2.1.5 on 2019-01-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_auto_20190112_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='text',
            field=models.TextField(default='', help_text='text of the log entry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='founded',
            field=models.DateField(blank=True, help_text='date when the station was founded', null=True, verbose_name='founding date'),
        ),
    ]
