# Generated by Django 2.1.5 on 2019-01-12 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_auto_20190112_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
