# Generated by Django 2.1.5 on 2019-01-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_auto_20190115_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name'], 'verbose_name': 'station'},
        ),
        migrations.AlterModelOptions(
            name='subnetwork',
            options={'ordering': ['id'], 'verbose_name': 'subnetwork'},
        ),
        migrations.AddField(
            model_name='subnetwork',
            name='founded',
            field=models.DateField(blank=True, help_text='date when the station was founded', null=True, verbose_name='founding date'),
        ),
    ]
