# Generated by Django 2.1.5 on 2019-01-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_auto_20190115_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(blank=True, help_text='printable full address', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(help_text='a simple unique code (2-4 uppercase letters)', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='subnetwork',
            name='founded',
            field=models.DateField(blank=True, help_text='date when the subnetwork was founded', null=True, verbose_name='founding date'),
        ),
    ]
