# Generated by Django 2.1.5 on 2019-01-27 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_auto_20190122_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='timezone',
            field=models.FloatField(default=0, help_text='time zone at the station', validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(12)], verbose_name='time zone'),
        ),
    ]
