# Generated by Django 2.1.5 on 2019-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_auto_20190127_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('pytzName', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': ('time zones',),
                'verbose_name': ('time zone',),
            },
        ),
        migrations.RemoveField(
            model_name='station',
            name='timezone',
        ),
    ]
