# Generated by Django 2.1.5 on 2019-01-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_auto_20190128_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='timezone',
        ),
        migrations.DeleteModel(
            name='TimeZone',
        ),
    ]
