# Generated by Django 2.2.3 on 2019-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0020_auto_20190128_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnetwork',
            name='code',
            field=models.CharField(default='a', help_text='a simple unique code (2-4 uppercase letters)', max_length=8),
            preserve_default=False,
        ),
    ]
