# Generated by Django 2.2.3 on 2019-07-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0022_auto_20190711_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('received', models.DateTimeField(verbose_name='received at')),
                ('status', models.CharField(max_length=64)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
            ],
            options={
                'verbose_name': 'status report',
                'verbose_name_plural': 'status reports',
            },
        ),
    ]
