# Generated by Django 2.2.3 on 2019-07-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0025_auto_20190715_0953'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statusreport',
            index=models.Index(fields=['station', 'timestamp'], name='stations_st_station_801c73_idx'),
        ),
    ]
