# Generated by Django 2.2.3 on 2019-07-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0026_auto_20190715_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusreport',
            options={'get_latest_by': ['timestamp'], 'verbose_name': 'status report', 'verbose_name_plural': 'status reports'},
        ),
        migrations.AlterModelOptions(
            name='subnetwork',
            options={'ordering': ['founded'], 'verbose_name': 'subnetwork'},
        ),
        migrations.AlterField(
            model_name='station',
            name='subnetwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='stations.Subnetwork'),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stations.Station'),
        ),
    ]
