# Generated by Django 2.2.3 on 2019-07-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0028_statusreport_lid'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='heating',
            field=models.CharField(blank=True, choices=[('1', 'On'), ('0', 'Off'), ('P', 'Problem')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='station',
            field=models.ForeignKey(blank=True, help_text='the station in question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stations.Station', verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='lid',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Closed'), ('P', 'Problem')], max_length=1, null=True),
        ),
    ]
