# Generated by Django 2.2.7 on 2019-11-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0030_auto_20190718_1430'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statusreport',
            name='stations_st_station_801c73_idx',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='station',
            field=models.ForeignKey(blank=True, help_text='the station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stations.Station', verbose_name='station'),
        ),
        migrations.AddIndex(
            model_name='statusreport',
            index=models.Index(fields=['timestamp', 'station'], name='stations_st_timesta_83cb25_idx'),
        ),
    ]
