# Generated by Django 2.2.7 on 2019-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0031_auto_20191113_1531'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='station',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), name='coordinates'),
        ),
    ]
