# Generated by Django 2.2.7 on 2019-11-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0032_auto_20191113_1536'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statusreport',
            name='stations_st_timesta_83cb25_idx',
        ),
        migrations.AddIndex(
            model_name='statusreport',
            index=models.Index(fields=['timestamp'], name='stations_st_timesta_704c57_idx'),
        ),
        migrations.AddIndex(
            model_name='statusreport',
            index=models.Index(fields=['station'], name='stations_st_station_00d0fa_idx'),
        ),
    ]
