# Generated by Django 2.2.7 on 2019-11-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0034_auto_20191113_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusreport',
            options={'get_latest_by': ['timestamp'], 'ordering': ['-timestamp'], 'verbose_name': 'status report', 'verbose_name_plural': 'status reports'},
        ),
        migrations.AlterField(
            model_name='logentry',
            name='station',
            field=models.ForeignKey(blank=True, help_text='the station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='stations.Station', verbose_name='station'),
        ),
    ]
