# Generated by Django 2.2.7 on 2019-11-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0035_auto_20191119_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='heating',
            field=models.CharField(blank=True, choices=[('0', 'off'), ('1', 'on'), ('P', 'problem')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='lid',
            field=models.CharField(blank=True, choices=[('O', 'open'), ('C', 'closed'), ('P', 'problem'), ('U', 'unknown')], max_length=1, null=True),
        ),
    ]
