# Generated by Django 3.0.5 on 2020-04-30 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0038_auto_20200417_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL, verbose_name='author of the entry'),
        ),
    ]
