# Generated by Django 3.0.5 on 2020-05-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0039_logentry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='on',
            field=models.BooleanField(default=False),
        ),
    ]
