# Generated by Django 3.0.8 on 2020-07-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0041_auto_20200722_1808'),
        ('stations', '0043_auto_20200725_1734'),
    ]

    operations = [
    ]
