# Generated by Django 3.1 on 2020-08-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0044_merge_20200729_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
