# Generated by Django 3.1.1 on 2020-09-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0045_logentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'observing'), ('M', 'malfunction'), ('N', 'not observing'), ('U', 'unknown')], default='U', max_length=1, null=True),
        ),
    ]
