# Generated by Django 3.1.1 on 2020-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0046_auto_20200922_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='lid',
            field=models.CharField(blank=True, choices=[('O', 'open'), ('C', 'closed'), ('P', 'problem'), ('U', 'unknown'), ('S', 'safety')], max_length=1, null=True),
        ),
    ]
