# Generated by Django 3.1.1 on 2020-10-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0047_auto_20200925_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartbeat',
            old_name='lid',
            new_name='cover_state',
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='cover_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='heating',
            field=models.CharField(blank=True, choices=[('0', 'off'), ('1', 'on'), ('?', 'unknown')], max_length=1, null=True),
        ),
    ]
