# Generated by Django 3.0.8 on 2020-11-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0049_auto_20201012_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartbeat',
            name='pressure',
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='lens_heating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='servo_direction_opening',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='servo_moving',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='t_cpu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='t_lens',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
