# Generated by Django 3.1.1 on 2020-11-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0050_auto_20201109_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartbeat',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='heartbeat',
            name='servo_direction_opening',
        ),
        migrations.RemoveField(
            model_name='heartbeat',
            name='servo_moving',
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='camera_heating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='computer_power',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='fan_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='intensifier_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='light_sensor_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='rain_sensor_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='status_string',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='cover_state',
            field=models.CharField(blank=True, choices=[('O', 'open'), ('o', 'opening'), ('C', 'closed'), ('c', 'closing'), ('P', 'problem'), ('U', 'unknown'), ('S', 'safety')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'observing'), ('N', 'not observing'), ('M', 'malfunction'), ('U', 'unknown')], default='U', max_length=1, null=True),
        ),
    ]
