# Generated by Django 3.1.1 on 2020-11-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0052_auto_20201109_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
    ]
