# Generated by Django 3.1.3 on 2021-01-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0053_auto_20201130_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartbeat',
            name='status',
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='state',
            field=models.CharField(blank=True, choices=[('O', 'observing'), ('N', 'not observing'), ('D', 'day'), ('M', 'manual'), ('U', 'dome unreachable'), ('R', 'rain or humidity'), ('?', 'unknown')], max_length=1, null=True),
        ),
    ]
