# Generated by Django 3.1.3 on 2021-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0054_auto_20210125_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='cover_position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
