# Generated by Django 3.1.3 on 2021-01-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0055_auto_20210128_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='rain_emergency_closing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
