# Generated by Django 3.1.3 on 2021-01-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0056_heartbeat_rain_emergency_closing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='storage_permanent_available',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='storage_permanent_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='storage_primary_available',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='storage_primary_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
