# Generated by Django 2.1.5 on 2019-01-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meteor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='absolute magnitude')),
                ('beginningLatitude', models.FloatField(blank=True, null=True, verbose_name='latitude of trail beginning')),
                ('beginningLongitude', models.FloatField(blank=True, null=True, verbose_name='longitude of trail beginning')),
                ('beginningAltitude', models.FloatField(blank=True, null=True, verbose_name='altitude of trail beginning')),
                ('beginningTime', models.DateTimeField(blank=True, null=True, verbose_name='timestamp of trail beginning')),
                ('lightmaxLatitude', models.FloatField(blank=True, null=True, verbose_name='latitude of point of maximum brightness')),
                ('lightmaxLongitude', models.FloatField(blank=True, null=True, verbose_name='longitude of point of maximum brightness')),
                ('lightmaxAltitude', models.FloatField(blank=True, null=True, verbose_name='altitude of point of maximum brightness')),
                ('lightmaxTime', models.DateTimeField(blank=True, null=True, verbose_name='timestamp of point of maximum brightness')),
                ('endLatitude', models.FloatField(blank=True, null=True, verbose_name='latitude of trail end')),
                ('endLongitude', models.FloatField(blank=True, null=True, verbose_name='longitude of trail end')),
                ('endAltitude', models.FloatField(blank=True, null=True, verbose_name='altitude of trail end')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='timestamp of trail end')),
                ('velocityX', models.FloatField(blank=True, null=True, verbose_name='geocentric velocity at infinity, x')),
                ('velocityY', models.FloatField(blank=True, null=True, verbose_name='geocentric velocity at infinity, y')),
                ('velocityZ', models.FloatField(blank=True, null=True, verbose_name='geocentric velocity at infinity, z')),
            ],
            options={
                'verbose_name': 'meteor',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='absolute magnitude')),
                ('beginningElevation', models.FloatField(blank=True, null=True)),
                ('beginningAzimuth', models.FloatField(blank=True, null=True)),
                ('beginningTime', models.DateTimeField(blank=True, null=True, verbose_name='time of beginning')),
                ('lightmaxElevation', models.FloatField(blank=True, null=True, verbose_name='elevation of point of maximum brightness')),
                ('lightmaxAzimuth', models.FloatField(blank=True, null=True, verbose_name='azimuth of point of maximum brightness')),
                ('lightmaxTime', models.DateTimeField(blank=True, null=True)),
                ('endElevation', models.FloatField(blank=True, null=True)),
                ('endAzimuth', models.FloatField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('angularSpeed', models.FloatField(blank=True, null=True)),
                ('solarElongation', models.FloatField(blank=True, null=True, verbose_name='solar elongation')),
                ('lunarElongation', models.FloatField(blank=True, null=True, verbose_name='lunar elongation')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.Station', verbose_name='observer location')),
                ('meteor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='meteors.Meteor')),
                ('observer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.Observer', verbose_name='observer')),
            ],
            options={
                'verbose_name': 'meteor sighting',
                'ordering': ['lightmaxTime'],
            },
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sighting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meteors.Sighting')),
            ],
            options={
                'verbose_name': 'meteor video frame',
            },
        ),
    ]
