# Generated by Django 2.1.5 on 2019-01-12 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0002_auto_20190112_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='observer',
        ),
    ]
