# Generated by Django 2.1.5 on 2019-01-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0003_remove_sighting_observer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'meteor shower',
            },
        ),
        migrations.AddField(
            model_name='meteor',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meteors.Shower', verbose_name='meteor shower'),
        ),
    ]
