# Generated by Django 2.2 on 2019-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0008_auto_20190329_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteor',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='name'),
            preserve_default=False,
        ),
    ]
