# Generated by Django 2.2 on 2019-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0009_meteor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteor',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
    ]
