# Generated by Django 2.2 on 2019-04-16 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0011_sighting_composite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sighting',
            options={'ordering': ['lightmaxTime', 'station__code'], 'verbose_name': 'meteor sighting'},
        ),
        migrations.AlterField(
            model_name='sighting',
            name='composite',
            field=models.ImageField(blank=True, null=True, upload_to='sightings/'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='lightmaxAltitude',
            field=models.FloatField(default=90, verbose_name='altitude at max light'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sighting',
            name='lightmaxAzimuth',
            field=models.FloatField(default=0, verbose_name='azimuth at max light'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sighting',
            name='lightmaxTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='timestamp at max light'),
            preserve_default=False,
        ),
    ]
