# Generated by Django 2.2 on 2019-04-19 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0013_auto_20190416_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteors.Sighting')),
            ],
            options={
                'verbose_name': 'sighting frame',
                'ordering': ['sighting__id', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['sighting', 'order'], name='sightingOrder'),
        ),
        migrations.AddConstraint(
            model_name='frame',
            constraint=models.UniqueConstraint(fields=('sighting', 'order'), name='frameOrdering'),
        ),
    ]
