# Generated by Django 2.2.5 on 2019-10-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0024_auto_20190721_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='angularSpeed',
            new_name='angular_speed',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='stations.Station', verbose_name='station'),
        ),
    ]
