# Generated by Django 2.2.5 on 2019-10-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0026_auto_20191030_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteor',
            old_name='velocityX',
            new_name='velocity_x',
        ),
        migrations.RenameField(
            model_name='meteor',
            old_name='velocityY',
            new_name='velocity_y',
        ),
        migrations.RenameField(
            model_name='meteor',
            old_name='velocityZ',
            new_name='velocity_z',
        ),
    ]
