# Generated by Django 2.2.5 on 2019-10-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteors', '0027_auto_20191030_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
    ]
